os:
  - osx

sudo:
  - false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - python3
      - java
      - clang
      - clang++

install:
 - brew tap caskroom/cask
 - brew tap caskroom/versions
 - brew cask install java8
 - brew tap facebook/fb
 - brew install watchman
 - brew install buck

script:
 - buck build :hello
 - buck run :hello
